#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 02:37:11 2020

@author: david
"""
import cv2
v= cv2.VideoCapture(1, cv2.CAP_V4L2)

v.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))

width = 1920
height = 1080
v.set(cv2.CAP_PROP_FRAME_WIDTH, width)
v.set(cv2.CAP_PROP_FRAME_HEIGHT, height)


width_2 = 1920//2
height_2 = 1080//2


while True:
    ret,frame=v.read()
    frame=cv2.resize(frame,(width_2,height_2),interpolation= cv2.INTER_AREA)
    if not ret:
        break
        
    cv2.imshow("Frame",frame)
    if cv2.waitKey(2) & 0xFF == ord('q'):
        break
v.release()
cv2.destroyAllWindows()