#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 02:37:11 2020

@author: david
"""
import cv2
v= cv2.VideoCapture(2)
while True:
    ret,frame=v.read()
    frame=cv2.resize(frame,(720,480),interpolation= cv2.INTER_AREA)
    if not ret:
        break
        
    cv2.imshow("Frame",frame)
    if cv2.waitKey(2) & 0xFF == ord('q'):
        break
v.release()
cv2.destroyAllWindows()