#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 01:22:33 2020

@author: david
"""
import cv2
import json
from Imagegather import correct_image

Positions=[]
bbx=[]
def click_event(event,x,y,flags,param):

        font=cv2.FONT_HERSHEY_SIMPLEX
        Positions.append([x,y])
        RB="({},{})".format(x,y)
        cv2.putText(frame, RB, (x, y), 
                    font, 0.4,  
                    (0, 255, 255), 
                    2) 
        cv2.imshow('image', frame) 
        
        

#v=cv2.VideoCapture(r'/home/david/mythesis/VID_20201201_203106.mp4')
v= cv2.VideoCapture(1)

v.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))

width = 1920
height = 1080
v.set(cv2.CAP_PROP_FRAME_WIDTH, width)
v.set(cv2.CAP_PROP_FRAME_HEIGHT, height)


width_2 = 1920//2
height_2 = 1080//2

ret,frame=v.read()
frame=cv2.resize(frame,(width_2,height_2),interpolation = cv2.INTER_AREA) 


cv2.imshow('image', frame)
cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

image2=correct_image(frame,Positions)

Tracking=int(input("Cantidad de robots a seguir: "))
for i in range (Tracking):
    cv2.imshow('frame',image2)
    
    bbi=cv2.selectROI('frame',image2)
    bbx.append(bbi)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
v.release()
Json={"Puntos":Positions,"Bboxs":bbx}

with open('points_bbx.txt', 'w') as outfile:
    json.dump(Json, outfile)