#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 01:22:33 2020

@author: david
"""
import cv2
import json
from Imagegather import correct_image

Positions=[]
bbx=[]
def click_event(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN:
        font=cv2.FONT_HERSHEY_SIMPLEX
        Positions.append([x,y])
        RB="({},{})".format(x,y)
        cv2.putText(image, RB, (x, y), 
                    font, 0.4,  
                    (0, 255, 255), 
                    2) 
        cv2.imshow('image', image) 
        
        

#v=cv2.VideoCapture(r'/home/david/mythesis/VID_20201201_203106.mp4')
v= cv2.VideoCapture(2)
ret,frame=v.read()
image=cv2.resize(frame,(720,480),interpolation = cv2.INTER_AREA) 
cv2.imshow('image', image)
cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()

image2=correct_image(image,Positions)

Tracking=int(input("Cantidad de robots a seguir: "))
for i in range (Tracking):
    cv2.imshow('frame',image2)
    
    bbi=cv2.selectROI('frame',image2)
    bbx.append(bbi)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
v.release()
Json={"Puntos":Positions,"Bboxs":bbx}

with open('points_bbx.txt', 'w') as outfile:
    json.dump(Json, outfile)